{% set version = "4.0.2" %}

package:
  name: social-auth-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/social-auth-core/social-auth-core-{{ version }}.tar.gz
  sha256: 604798ec00a49a84f7a173460c5997c5409080e64acc8a47e2eefd6f59439a15

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - cryptography >=1.4
    # [py>=3]
    - defusedxml >=0.5.0rc1
    - oauthlib >=1.0.3
    - pyjwt >=1.4.0,<2
    # [py>=3]
    - python3-openid >=3.0.10
    - requests >=2.9.1
    - requests-oauthlib >=0.6.1
    - six >=1.10.0


test:
  imports:
    - social_core
    - social_core.backends
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://github.com/python-social-auth/social-core
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python social authentication made simple

extra:
  recipe-maintainers:
    - ocefpaf
