{% set version = "3.1.0" %}

package:
  name: social-auth-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/social-auth-core/social-auth-core-{{ version }}.tar.gz
  sha256: cc871fb4528f7cbba67efdba0bc0f7d7c6eeb92113b0cdc9368dd91ffe965782

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - requests >=2.9.1
    - oauthlib >=1.0.3
    - requests-oauthlib >=0.6.1
    - six >=1.10.0
    - pyjwt >=1.4.0
    - defusedxml >=0.5.0rc1
    - python3-openid >=3.0.10

test:
  imports:
    - social_core
    - social_core.backends
    - social_core.pipeline
    - social_core.tests
    - social_core.tests.actions
    - social_core.tests.backends
    - social_core.tests.backends.data

about:
  home: https://github.com/python-social-auth/social-core
  license: BSD 3-clause
  summary: 'Python social authentication made simple.'

extra:
  recipe-maintainers:
    - ocefpaf
