travis:
  secure:
    BINSTAR_TOKEN: FZumILcECYqeqzo9zB10pcLqt0ik2WDi13KI9GAb2Bg6HeJiq1DSLDkLdzcNi5VTgsIB4Wp+qzK2ranElLih13bBhD9b71gOp9OJ/32RWHhdEYzsYcmuosy1/mUfcoqBJ2G016VAX0v0ZPXPnR8LvES3hLuYbCGIwVrT6PSX6VJa4YXtozJYWAwKfHPDEuVXA4w05EvOYRK5HMfXEsDCNQtNn77G4GIVZQ5tN93CWQDxN16ISq+hU9P3qsWLNEdDYVRVwMtbWwPJ8Zi7cMeZiPmeTrx4w3HwnEdA9kgMwqmifYOLCqNwyI5ht8KnkTaoKzqKMFhjtrnZzBZtgffHABDZqjTobWEdDcJi0FkisQoUDF/WKiT3YmE64UO9aG5bXrLbvwDvk719GSPa/8cRz761scEOYADR9mQXvwJoeTCHmDNmgEtJbT5i70dIb4fZwgqhj1Eog6DQnfr62/Yb7Mk1KS8Fnx/gcbfujQF23zqiytHZqwHtCn+JkmIyKGIDh7pGLYbmI/Fv8/K5nvmWrZ4h3oG6VT7sF/BqXxiIu8lsTPKt+sPORRaqw52RLSdO1EZcyUy/zCcT2KjrlzPbcXoXvucREAoCyQgYpOSeaXOyfXOy+Ib9QcdVrUmQ72H+ttlkdMG6CjGhD5Fd43ZDrrB/NDAPLkbKJlxWTUCG49Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
