travis:
  secure:
    BINSTAR_TOKEN: O5yGA55Wjf+l3ODKgPq+RzLz00gpGxNDACkj58I8sosIjOPH9H6rx4n2qt88K/y9fPfjT8g1aXzfZEylbUzL0LE0fshC0VT9AKPrALd4sS6Juaybc/R+5mXrTSNhKSxOE5nfezQM5BWWbPa5iRMFz8cG2w3z7oLzRxNzWUO0GJNbJRHq3JRrbkBtIxlnkjwJczNx5mp6JXqpW0YrTa0kBemlqEHIWgsxqSk0w8ICxbieICPcvUlTGk+vjjkbvDJO8L9GN+SlEwaC5AI7wHmQBR8YkziUQCDm/XCMiwQ2NjWgV/DipBfV++5uJuwnDSg7ezpVkuczLmQyE1OedYxr25MKlBYmAmPMGKpZsif+GJMb0K3VIVL16gNB8NjfEcF4216Nr7ALYgLum8HUNVJVqnI2A5adW6PIgBksbEUEpF1QQH/zQiJBzIvbfXnycwzMoGKDZZtcNhJhJWoSnMvEcJ1tuM0OMOpx5PXBEz3AkaB5wKgOtNSwMdwVWwd7Tz4PN4gZ13OA7zxG92+bUAwdF6+Bj4ug9134XszSXGXMwy7lC/qc9CTG1JgRdYs9icXoBNTPnuksPFo03epYb7Wy6afnCfC9ot0eiz067aIXATNNwGZ3fjbUFT20APDAw1Id1wF1sduu25q4DBiO8r5Fl6nIfSx9kpcbZG0FC3lEOwk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
